FROM php:8.4-apache

ENV ALLOW_OVERRIDE=true

RUN docker-php-ext-install mysqli
RUN apt-get update && \
apt-get install libldap2-dev -y && \
rm -rf /var/lib/apt/lists/* && \
docker-php-ext-configure ldap && \
docker-php-ext-install ldap
RUN apt-get update && \
	apt-get install -y --no-install-recommends sudo curl libmosquitto-dev && \
	curl -sSL https://github.com/nismoryco/Mosquitto-PHP/archive/refs/tags/0.5.0.tar.gz | tar -C /tmp -xvzpf - && \
	(cd /tmp/Mosquitto-PHP-0.5.0 && phpize && ./configure && make && make install) && rm -R /tmp/Mosquitto-PHP-0.5.0 && \
	docker-php-ext-enable mosquitto
RUN a2enmod ssl proxy proxy_wstunnel
RUN curl -sSL https://get.docker.com/ | sh
RUN mkdir /ccache ; chmod 777 /ccache
ADD conf/web/.gitconfig /var/www/.gitconfig

